#!/usr/bin/env python3
"""Generate LEADERBOARD.md from measurements/*.jsonl + corpus/manifest.jsonl.

Groups rows by (language, backend, model, chip) — language joined from the
corpus manifest, backend/model split from model_id ("backend|family|size|
quant"). Reports median error rate ± MAD, median x-realtime, contributor and
machine counts. Numbers are SELF-REPORTED; the header says so explicitly.
Stdlib only. Usage: leaderboard.py [repo_root] (writes LEADERBOARD.md there).
"""
import glob
import json
import os
import statistics
import sys


def load_jsonl(path):
    if not os.path.exists(path):
        return
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                try:
                    yield json.loads(line)
                except json.JSONDecodeError:
                    pass


def main():
    repo = sys.argv[1] if len(sys.argv) > 1 else "."
    corpus_lang = {
        row["corpus_id"]: row.get("language", "?")
        for row in load_jsonl(os.path.join(repo, "corpus", "manifest.jsonl"))
    }
    groups = {}
    for path in sorted(glob.glob(os.path.join(repo, "measurements", "*.jsonl"))):
        for row in load_jsonl(path):
            parts = str(row.get("model_id", "")).split("|")
            backend = parts[0] if parts else "?"
            model = parts[2] if len(parts) > 2 else "?"
            lang = corpus_lang.get(row.get("corpus_id"), "?")
            key = (lang, backend, model, row.get("chip", "?"))
            groups.setdefault(key, {"err": [], "rtf": [], "contributors": set(), "machines": set(),
                                    "metric": row.get("metric_kind", "?")})
            g = groups[key]
            if isinstance(row.get("error_rate"), (int, float)):
                g["err"].append(row["error_rate"])
            if isinstance(row.get("rtf"), (int, float)) and row["rtf"] > 0:
                g["rtf"].append(1.0 / row["rtf"])
            g["contributors"].add(row.get("contributor", "?"))
            g["machines"].add(row.get("machine_id", "?"))

    lines = [
        "# Leaderboard",
        "",
        "**Self-reported** community measurements — median ± MAD over N rows;",
        "see the trust model in README.md. Regenerated by `tools/leaderboard.py`.",
        "",
        "| Language | Backend | Model | Chip | Metric | Median err ± MAD | Median ×RT | Rows | Contributors | Machines |",
        "|---|---|---|---|---|---|---|---|---|---|",
    ]
    def sort_key(item):
        (lang, backend, model, chip), g = item
        med = statistics.median(g["err"]) if g["err"] else 1.0
        return (lang, med, backend, model, chip)
    for (lang, backend, model, chip), g in sorted(groups.items(), key=sort_key):
        if g["err"]:
            med = statistics.median(g["err"])
            mad = statistics.median(abs(v - med) for v in g["err"])
            err = f"{med * 100:.1f}% ± {mad * 100:.1f}"
        else:
            err = "—"
        rt = f"{statistics.median(g['rtf']):.1f}x" if g["rtf"] else "—"
        lines.append(
            f"| {lang} | {backend} | {model} | {chip} | {g['metric']} | {err} | {rt} "
            f"| {len(g['err'])} | {len(g['contributors'])} | {len(g['machines'])} |")
    if not groups:
        lines.append("| _no measurements yet_ | | | | | | | | | |")
    out = os.path.join(repo, "LEADERBOARD.md")
    with open(out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {out} ({len(groups)} group(s))")
    return 0


if __name__ == "__main__":
    sys.exit(main())
